package com.mykaimeal.planner.messageclass

object ApiEndPoint {

    const val bodyGoals="body_goals"
    const val dietaryRestrictions="dietary_restrictions"
    const val favouriteCuisines="favourite_cuisines"
    const val dislikeIngredients="dislike_ingredients"
    const val allergensIngredients="allergens_ingredients"
    const val mealRoutine="meal_routine"
    const val cookingFrequency="cooking_frequency"
    const val eatingOut="eating_out"
    const val tipUrl="tip"
    const val takeAwayReason="take_away_reason"
    const val userSignup="user-signup"
    const val otpVerify="otp-verify"
    const val forgotPassword="user-forgot-Password"
    const val forgotOtpVerify="forget-otp-verify"
    const val resendOtp="resenddotp"
    const val updatePassword="update-password"
    const val userLogin="user-login"
    const val socialLogin="social_login"
    const val updateLocation="update-Location"
    const val updateNotification="toggle-notification"

    const val saveFeedback="save-feedback"
    const val termsCondition="terms-and-condation"
    const val privacyPolicy="privacy-policy"

    const val userProfileUrl="get-user-profile"
    const val userProfileUpdateUrl="user-profile-update"
    const val userImageUpdateUrl="profile-img-update"
    const val  addCardUrl="add-Card"
    const val getCardBankUrl="user-bank-and-card-list"
    const val deleteCardUrl="delete_card"
    const val deleteBankUrl="delete-Bank-Account"
    const val countriesUrl="get-countries"
    const val transferToAccountUrl="transfer-To-Account"
    const val bankAddUrl="add-bank-details"
    const val walletAmountUrl="get-wallet"
    const val logOutUrl="user-Logout"
    const val deleteUrl="user-delete"
    const val updateNotificationUrl="update-notification"
    const val recipeDetailsUrl="get-recipe"
    const val mealReviewUrl="meal-review"
    const val homeUrl="home-data"
    const val allRecipeUrl="all-recipe"
    const val getMealsUrl="get-meals"
    const val likeUnlikeUrl="add-to-favorite"
    const val storeUUIDUrl="update-user-prefrence"
    const val moveRecipeUrl="move-recipe"
    const val removeCookBookUrl="remove-cook-book"
    const val addBasketeUrl="add-to-basket"
    const val addBasketeDetailsUrl="ingredient-basket"

    const val  getUserPreferences="user-prefrence"
    const val  getSubscriptionDeltailsUrl="getSubscriptionDeltails"

    const val  updateUserPreferences="update-user-prefrence"
    const val recipeSearch="recipe"

    const val createRecipeUrl="recipes"

    const val addMealUrl="add-meal"
    const val addMealTypeUrl="add-meal-type"
    const val createMealUrl="create-meal"
    
    const val getCookBookUrl="get-cook-book"
    const val cookBookTypeListUrl="cook-book-type-list"

    const val createCookBook="add-cook-book"

    const val removeMeal="remove-meal"
    const val removeBasketUrl="remove-basket"
    const val getMissingIngUrl="get-missing-ingredient"
    const val forSearchUrl="for-search"
    const val addToCartUrl="add-to-cart"
    const val forPreferenceUrl="for-preference-update"
    const val getSchedule="get-schedule"
    const val getMealByUrl="get-meal-by-url"
    const val updateMealUrl="update-meal"
    const val filterSearchUrl="for-filter-search"
    const val superMarketsUrl="super-markets"
    const val superMarketsPageUrl="super-markets2"
    const val checkavailablityUrl="checkavailablity"
    const val subscriptionGoogleUrl="subscription/google"
    const val checkSubscriptionUrl="checkSubscription"
    const val getAddressUrl="get-address"
    const val addAddressUrl="add-address"
    const val makeAddressPrimaryUrl="make-address-primary"
    const val getBasketListUrl="get-basketlist"
    const val getYourRecipeUrl="your-recipe"
    const val getSendSmsUrl="send-sms"
    const val addPhoneUrl="add-phone"
    const val getShoppingListUrl="shopping-list"
    const val addNotesUrl="add-notes"
    const val getNotesUrl="get-notes"
    const val getCheckoutUrl="checkout"
    const val getOrderProductUrl="order-product"
    const val chargeUrl="charge"

    const val getStoreProductsUrl="store-products"
    const val getCardMealMeUrl="get-card-mealme"
    const val addCardMealMeUrl="add-card-mealme"
    const val deleteCardMealMeUrl="delete-card-mealme"
    const val setPreferredCardMealMeUrl="set-preferred-card"

    const val getProductsUrl="products"
    const val getProductsDetailsUrl="get-products"

    const val getSelectProductsUrl="select-product"
    const val getAllIngredientsUrl="ingredients"

    const val recipeSwapUrl="swap"
    const val basketYourRecipeIncDescUrl="add-to-basket"
    const val basketIngIncDescUrl="change-cart"

    const val addToBasketAllUrl="add-to-basket-all"
    const val userDietSuggestionUrl="user-diet-suggetion"
    const val generateLinkUrl="generate-link"
    const val selectStoreProductUrl="select-store-product"

    const val getMissingIngBasketUrl="get-missing-ingredient-screen"
    const val graph="graph"
    const val orderHistoryUrl="order-history"
    const val graphWeekUrl="graph-week"
    const val referralUrl="referral"
    const val reedemUrl="reedem"

}