package com.mykaimeal.planner.basedata

class AppConstant {
    companion object {
        const val FEEDBACK: String="Feedback"
        const val COMPLAINT: String="Complaint"
        const val OTHERS: String="Others"
        const val loginSession: String="session"
        const val Premium_Monthly: String="monthly_plan"
        const val Premium_Annual: String="annual_plan"
        const val Premium_Weekly: String="weekly_plan"
        const val Preferences: String="Preferences"
        const val SubscriptionId: String="SubscriptionId"
        const val PurchaseToken: String="PurchaseToken"
        const val planType: String="planType"
        const val rememberMe: String="RememberMe"
        const val SessionFirstTime: String="sessionFirstTime"
        const val checkTypeSession: String="CheckType"
        const val jobId: String="JobId"
        const val cookingFor: String="CookingFor"
        const val cookingScreen: String="CookingScreen"
        const val authToken: String="Token"
        const val LOGIN_SESSION:String="login_session"
        const val FirstTime:String="FirstTime"
        const val RememberMe:String="RememberMe"
        val Id: String="ID"
        val NAME: String ="NAME"
        val Address: String ="UserAddress"
        val Latitude: String ="latitude"
        val Longitude: String ="longitude"

        val userId: String ="UserId"
        val CookBookName: String ="CookBookName"
        val ProviderName: String ="ProviderName"
        val ProviderImage: String ="ProviderImage"
        val CookBookId: String ="CookBookId"
        val CookBookUsingShare: String ="CookBookUsingShare"
        val CookBookImage: String ="CookBookImage"
        val CookBookType: String ="CookBookType"
        const val Gender: String ="Gender"
        const val EMAIL :String ="Email"
        const val PHONE :String ="Phone"
        const val Image :String ="Image"

        const val PartnerName: String ="PartnerName"
        const val ReferralCode: String ="RefferalCode"
        const val PartnerAge: String ="PartnerAge"
        const val PartnerGender: String ="PartnerGender"
        const val FamilyMemName: String ="FamilyMemName"
        const val FamilyMemAge: String ="FamilyMemAge"
        const val FamilyStatus: String ="FamilyStatus"
        const val BodyGoal: String ="BodyGoal"
        const val DietaryRestriction: String ="DietaryRestriction"
        const val FavouriteCuisine: String ="FavouriteCuisine"
        const val DislikeIngredient: String ="DislikeIngredient"
        const val AllergenIngredient: String ="AllergenIngredient"
        const val MealRoutine: String ="MealRoutine"
        const val CookingFrequency: String ="CookingFrequency"
        const val SpendingAmount: String ="SpendingAmount"
        const val SpendingDuration: String ="SpendingDuration"
        const val EatingOut: String ="EatingOut"
        const val ReasonForTakeAway: String ="ReasonForTakeAway"
        const val ReasonForTakeAwyDesc: String ="ReasonForTakeAwayDesc"

    }
}